apiVersion: v1
kind: Service
metadata:
  name: real-time-chat-service
spec:
  selector:
    app: real-time-chat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 # Specify the NodePort here
  type: NodePort

